apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  labels:
    app: auth-service
data:
  LOG_LEVEL: "4"

  HTTP_PORT: "8002"
  GRPC_PORT: "50051"

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "auth_db"
  POSTGRES_USER: "auth_user"
  POSTGRES_MAX_IDLE_CONNS: "10"
  POSTGRES_MAX_OPEN_CONNS: "100"
  POSTGRES_CONN_MAX_LIFETIME: "1h"

  RMQ_CONN_URL: "amqp://guest:guest@rabbitmq:5672/"
  RMQ_MAIL_EXCHANGE: "mail"
  RMQ_MAIL_EXCHANGE_AUTOCREATE_ENABLED: "true"

  REDIS_ADDR: "redis:6379"
  REDIS_DB: "0"

  S3_AVATARS_BUCKET_NAME: "avatars"
  S3_COVERS_BUCKET_NAME: "covers"
  S3_REGION: "us-east-1"
  S3_ENDPOINT: "http://minio:9000"

  MAX_FILE_UPLOAD_SIZE: "10485760"
